module Emarsys::FieldMapping

  ATTRIBUTES = [
    {:id => 0,   :identifier => 'interests',                  :name => 'Interests'},
    {:id => 1,   :identifier => 'first_name',                 :name => 'First Name'},
    {:id => 2,   :identifier => 'last_name',                  :name => 'Last Name'},
    {:id => 3,   :identifier => 'email',                      :name => 'E-Mail'},
    {:id => 4,   :identifier => 'date_of_birth',              :name => 'Date of Birth'},
    {:id => 5,   :identifier => 'gender',                     :name => 'Gender'},
    {:id => 6,   :identifier => 'marital_status',             :name => 'Marital Status'},
    {:id => 7,   :identifier => 'children',                   :name => 'Children'},
    {:id => 8,   :identifier => 'education',                  :name => 'Education'},
    {:id => 9,   :identifier => 'title',                      :name => 'Title'},
    {:id => 10,  :identifier => 'address',                    :name => 'Address'},
    {:id => 11,  :identifier => 'city',                       :name => 'City'},
    {:id => 12,  :identifier => 'region',                     :name => 'Region'},
    {:id => 13,  :identifier => 'zip',                        :name => 'ZIP Code'},
    {:id => 14,  :identifier => 'country',                    :name => 'Country'},
    {:id => 15,  :identifier => 'phone',                      :name => 'Phone'},
    {:id => 16,  :identifier => 'fax',                        :name => 'Fax'},
    {:id => 17,  :identifier => 'job_position',               :name => 'Job Position'},
    {:id => 18,  :identifier => 'company',                    :name => 'Company'},
    {:id => 19,  :identifier => 'department',                 :name => 'Department'},
    {:id => 20,  :identifier => 'industry',                   :name => 'Industry'},
    {:id => 21,  :identifier => 'phone_office',               :name => 'Phone (office)'},
    {:id => 22,  :identifier => 'fax_office',                 :name => 'Fax (office)'},
    {:id => 23,  :identifier => 'number_of_employees',        :name => 'Number of Employees'},
    {:id => 24,  :identifier => 'annual_revenue',             :name => 'Annual Revenue (in 000 EUR)'},
    {:id => 25,  :identifier => 'url',                        :name => 'URL'},
    {:id => 26,  :identifier => 'preferred_mail_format',      :name => 'Preferred Mail Format'},
    {:id => 27,  :identifier => 'avg_length_of_visit',        :name => 'Avg. length of visit (minutes)'},
    {:id => 28,  :identifier => 'page_views_per_day',         :name => 'Page views per day'},
    {:id => 29,  :identifier => 'days_since_last_email_sent', :name => 'Days since last e-mail sent'},
    {:id => 30,  :identifier => 'response_rate',              :name => 'Response rate (% of campaigns sent)'},
    {:id => 31,  :identifier => 'opt_in',                     :name => 'Opt-In'},
    {:id => 32,  :identifier => 'user_status',                :name => 'User status'},
    {:id => 33,  :identifier => 'contact_source',             :name => 'Contact source'},
    {:id => 34,  :identifier => 'contact_form',               :name => 'Contact form'},
    {:id => 35,  :identifier => 'registration_language',      :name => 'Registration Language'},
    {:id => 36,  :identifier => 'newsletter',                 :name => 'Newsletter'},
    {:id => 37,  :identifier => 'mobile',                     :name => 'Mobile'},
    {:id => 38,  :identifier => 'first_name_of_partner',      :name => 'First Name of Partner'},
    {:id => 39,  :identifier => 'birthdate_of_partner',       :name => 'Birthdate of Partner'},
    {:id => 40,  :identifier => 'anniversary',                :name => 'Anniversary'},
    {:id => 41,  :identifier => 'company_address',            :name => 'Company Address'},
    {:id => 42,  :identifier => 'zip_official',               :name => 'Zip Code (office)'},
    {:id => 43,  :identifier => 'city_official',              :name => 'City (office)'},
    {:id => 44,  :identifier => 'state_official',             :name => 'State (office)'},
    {:id => 45,  :identifier => 'country_official',           :name => 'Country (office)'},
    {:id => 46,  :identifier => 'salutation',                 :name => 'Salutation'},
    {:id => 47,  :identifier => 'email_valid',                :name => 'E-Mail valid'},
    {:id => 48,  :identifier => 'date_of_first_registration', :name => 'Date of first registration'}
  ]

end